DROP TABLE IF EXISTS P06_PiecePays CASCADE;

CREATE TABLE P06_PiecePays(
    PaysID  INT PRIMARY KEY AUTO_INCREMENT,
    PieceID INT NOT NULL, 
    PaysNom VARCHAR(250) NOT NULL,

    FOREIGN KEY (PieceID) REFERENCES P06_PieceModele(PieceID)
);
