DROP TABLE IF EXISTS P06_Collectionner CASCADE;

DROP TABLE IF EXISTS P06_Collectionneur CASCADE;

DROP TABLE IF EXISTS P06_PiecePays CASCADE;

DROP TABLE IF EXISTS P06_PieceTranche CASCADE;

DROP TABLE IF EXISTS P06_PieceCaracteristique CASCADE;

DROP TABLE IF EXISTS P06_PieceModele CASCADE ;

DROP VIEW IF EXISTS P06_PiecesNonPossedees ;

DROP VIEW IF EXISTS P06_CollectionneursInfos ;

DROP VIEW IF EXISTS P06_PieceInfos ;

