
-- DROP ALL THE TRIGGERS IF ANY 
-- DROP ALL THE FUNCTIONS IF ANY 

-- DROP ALL THE VIEWS IF ANY
DROP VIEW IF EXISTS P06_CollectionneursInfos;
DROP VIEW IF EXISTS P06_PiecesNonPossedees;
DROP VIEW IF EXISTS P06_PieceInfos;



-- DROP ALL THE JUNCTION TABLES IF ANY
DROP TABLE IF EXISTS P06_Collectionner;

-- DROP ALL THE TABLES IF ANY
DROP TABLE IF EXISTS P06_Collectionneur;
DROP TABLE IF EXISTS P06_PieceCaracteristique ;
DROP TABLE IF EXISTS P06_PiecePays;
DROP TABLE IF EXISTS P06_PieceTranche ;
DROP TABLE IF EXISTS P06_PieceModele ;

-- DROP THE DATABASE
DROP DATABASE P06_Euro;




